TASK: ssl_eval_ucf
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 20
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  CHECKPOINT_CLEAR_NAME_PATTERN: ("backbone.",)
  CHECKPOINT_EPOCH_RESET: True
#  CHECKPOINT_FILE_PATH: /home/markus/PycharmProjects/SlowFast/pretrained_models/SLOWONLY_8x8_R50.pkl
  CHECKPOINT_FILE_PATH: /root/pretrained_models/BYOL_SlowR50_8x8_T2_epoch_00200.pyth
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  SSL_COLOR_JITTER: True # default false
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_HUE: 0.1
  SSL_COLOR_BRI_CON_SAT: [0.4, 0.4, 0.4] # default [0.4, 0.4, 0.4]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /root/UCF-101/
  PATH_PREFIX: /root/UCF-101/
  DECODING_BACKEND: pyav
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
  NUM_SYNC_DEVICES: 1
  NORM_TYPE: "sync_batchnorm"
SOLVER:
  BASE_LR: 0.01
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 101
  MODEL_NAME: ResNet
  ARCH: slow
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.8
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
#  CHECKPOINT_FILE_PATH: ./ucf_finetune/checkpoints/ssl_eval_ucf_checkpoint_epoch_00010.pyth
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /root/ucf_results/byol_slow_r50_syn8_pretrained
