TASK: ssl
TRAIN:
  DATASET: kinetics
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  BATCH_SIZE: 6
MODEL:
  NUM_CLASSES: 101
  MODEL_NAME: ContrastiveModel
  ARCH: slow_c2d
  ARCH: slow
  LOSS_FUNC: contrastive_loss
  DROPOUT_RATE: 0.0
  HEAD_ACT: none
CONTRASTIVE:
  T: 0.5
  DIM: 101 # 128 default, if changed, change nCls too
  NUM_MLP_LAYERS: 2 # default 1
  BN_MLP: True
  BN_SYNC_MLP: True
  MLP_DIM: 4096
  SEQUENTIAL: True  # def fault
  MOMENTUM: 0.996 # default 0.5
  MOMENTUM_ANNEALING: True # default false
  TYPE: byol # default mem
  PREDICTOR_DEPTHS: [2]
  NUM_CLASSES_DOWNSTREAM: 101
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  # NUM_FRAMES: 16 # dont forget to change these parameters in linear & finetuning configs
  # SAMPLING_RATE: 4
  TRAIN_CROP_NUM_TEMPORAL: 2  # default 1
  TRAIN_CROP_NUM_SPATIAL: 1  # default 1
  TRAIN_JITTER_SCALES_RELATIVE: [0.2, 0.766]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  SSL_MOCOV2_AUG: True
  SSL_COLOR_JITTER: True # default false
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_HUE: 0.15
  SSL_COLOR_BRI_CON_SAT: [0.6, 0.6, 0.6] # default [0.4, 0.4, 0.4]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_LABEL_SEPARATOR: " "
#  PATH_TO_DATA_DIR: /home/markus/PycharmProjects/SlowFast/data/ucf/
#  PATH_PREFIX: /home/markus/PycharmProjects/SlowFast/data/ucf/
  PATH_TO_DATA_DIR: /root/UCF-101/
  PATH_PREFIX: /root/UCF-101/
  DECODING_SHORT_SIZE: 256
  DECODING_BACKEND: pyav
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
  NUM_SYNC_DEVICES: 1
  NORM_TYPE: "sync_batchnorm"
  # NORM_TYPE: "sync_batchnorm_apex"
SOLVER:
  # BASE_LR: 1.2 # for rho=4 clips
  BASE_LR: 0.6
  LARS_ON: True
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 35.0
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 6
  NUM_TEMPORAL_CLIPS: [1]
DATA_LOADER:
  NUM_WORKERS: 10
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0
OUTPUT_DIR: /root/ucf_results/byol_slow_r50_8x8
DETECTION:
  ENABLE: False