TASK: ssl_eval_k400
TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 1
  EVAL_PERIOD: 20
  CHECKPOINT_PERIOD: 20
  AUTO_RESUME: False
  CHECKPOINT_CLEAR_NAME_PATTERN: ("backbone.",)
  CHECKPOINT_TYPE: pytorch
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_FILE_PATH: ../pretrained_models/BYOL_SlowR50_8x8_T2_epoch_00200.pyth
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
#  PATH_TO_DATA_DIR: /home/markus/PycharmProjects/SlowFast/data/ucf/
#  PATH_PREFIX: /home/markus/PycharmProjects/SlowFast/data/ucf/
  PATH_TO_DATA_DIR: /root/all_behavior_videos
  PATH_PREFIX: /root/all_behavior_videos
  DECODING_BACKEND: pyav
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 50
  WEIGHT_DECAY: 0.0
  NUM_SYNC_DEVICES: 1
  NORM_TYPE: "sync_batchnorm_apex"
  NORM_TYPE: "sync_batchnorm"
SOLVER:
  BASE_LR: 0.5 # slightly better +0.3%
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 3
  LR_POLICY: cosine
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0 # 1e-4 default
  WARMUP_EPOCHS: 8.0
  WARMUP_START_LR: 0.0
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: slow
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.0
  DETACH_FINAL_FC: True
TEST:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: False
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /home/markus/Desktop/ssl_tests/byol_demo_linear/
#EMBEDDING:
##  ENABLE: False
#  ENABLE: True
#  PATH_TO_VIDEO_FOLDER: /home/markus/PycharmProjects/contrast_MAE/MABe/mouse_data/submission_videos_resized_224/submission_videos_mp4
#  PATH_TO_FRAME_MAP: /home/markus/PycharmProjects/mabe-2022-public-evaluator/round2/metadata/mouse_round2_frame_number_map.npy
DEMO:
  ENABLE: True
  INPUT_VIDEOS: /root/all_behaviors/
  THREAD_ENABLE: False
  BATCH_SIZE: 64
  OUTPUT_FILE: /root/results_stefanos_byol
  CHECKPOINT_FILE_PATH: /root/pretrained_models/BYOL_SlowR50_8x8_T4_epoch_00200.pyth
  CHECKPOINT_CLEAR_NAME_PATTERN: ("backbone.",)
  CHECKPOINT_TYPE: pytorch
  CLIP_LENGTH: 1800
  SUBSAMPLE: 5